---
settings:
  name: Cloud Manager 3.7
  nss_product: OnCommand Cloud Manager
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Cloud Manager 3.7
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Cloud Manager
      entries:
      - title: Novedades
        url: "/reference_new_occm.html"
      - title: Problemas conocidos
        url: "/reference_issues.html"
      - title: Limitaciones conocidas
        url: "/reference_limitations.html"
    - title: Cloud Volumes ONTAP
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/
  - title: Conceptos
    entries:
    - title: Información general del producto
      url: "/concept_overview.html"
    - title: Cloud Central de NetApp
      url: "/concept_cloud_central.html"
    - title: Cuentas de Cloud Central
      url: "/concept_cloud_central_accounts.html"
    - title: Cuentas de proveedores de cloud
      entries:
      - title: Cuentas de AWS
        url: "/concept_accounts_aws.html"
      - title: Cuentas de Azure
        url: "/concept_accounts_azure.html"
      - title: Cuentas GCP
        url: "/concept_accounts_gcp.html"
    - title: Reducida
      entries:
      - title: Discos y agregados
        url: "/concept_storage.html"
      - title: Organización en niveles de los datos
        url: "/concept_data_tiering.html"
      - title: Gestión del almacenamiento
        url: "/concept_storage_management.html"
      - title: Almacenamiento WORM
        url: "/concept_worm.html"
    - title: Pares de alta disponibilidad
      entries:
      - title: Parejas de HA en AWS
        url: "/concept_ha.html"
      - title: Parejas de HA en Azure
        url: "/concept_ha_azure.html"
    - title: Evaluación
      url: "/concept_evaluating.html"
    - title: Licencia
      url: "/concept_licensing.html"
    - title: Seguridad
      url: "/concept_security.html"
    - title: Rendimiento
      url: "/concept_performance.html"
  - title: Manos a la obra
    entries:
    - title: Información general sobre la implementación
      url: "/reference_deployment_overview.html"
    - title: Empiece a usar AWS
      url: "/task_getting_started_aws.html"
    - title: Empiece a usar Azure
      url: "/task_getting_started_azure.html"
    - title: Empiece a usar GCP
      url: "/task_getting_started_gcp.html"
    - title: Configure Cloud Manager
      entries:
      - title: Configure la cuenta de Cloud Central
        url: "/task_setting_up_cloud_central_accounts.html"
      - title: Añada cuentas AWS
        url: "/task_adding_aws_accounts.html"
      - title: Añada cuentas de Azure
        url: "/task_adding_azure_accounts.html"
      - title: Agregar cuentas GCP
        url: "/task_adding_gcp_accounts.html"
      - title: Añada cuentas del sitio de soporte de NetApp
        url: "/task_adding_nss_accounts.html"
      - title: Instale un certificado HTTPS
        url: "/task_installing_https_cert.html"
      - title: Configure el KMS de AWS
        url: "/task_setting_up_kms.html"
    - title: Requisitos de red
      entries:
      - title: Cloud Manager
        url: "/reference_networking_cloud_manager.html"
      - title: Cloud Volumes ONTAP para AWS
        url: "/reference_networking_aws.html"
      - title: Configure una puerta de enlace de tránsito de AWS
        url: "/task_setting_up_transit_gateway.html"
      - title: Cloud Volumes ONTAP para Azure
        url: "/reference_networking_azure.html"
      - title: Cloud Volumes ONTAP para GCP
        url: "/reference_networking_gcp.html"
    - title: Opciones adicionales de puesta en marcha
      entries:
      - title: Requisitos del host de Cloud Manager
        url: "/reference_cloud_mgr_reqs.html"
      - title: Instale Cloud Manager en Linux
        url: "/task_installing_linux.html"
      - title: Ponga en marcha Cloud Manager desde AWS Marketplace
        url: "/task_launching_aws_mktp.html"
      - title: Ponga en marcha Cloud Manager desde Azure Marketplace
        url: "/task_launching_azure_mktp.html"
      - title: Ponga en marcha Cloud Manager en una región Gov de Azure
        url: "/task_installing_azure_gov.html"
      - title: Ponga en marcha Cloud Manager en la región de Azure Alemania
        url: "/task_installing_azure_germany.html"
      - title: Empiece a usar AWS C2S
        url: https://docs.netapp.com/us-en/occm/media/c2s.pdf
    - title: Mantenga Cloud Manager en funcionamiento
      url: "/concept_keep_up.html"
  - title: Ponga en marcha Cloud Volumes ONTAP
    entries:
    - title: Antes de empezar
      url: "/reference_before.html"
    - title: Inicie sesión en Cloud Manager
      url: "/task_logging_in.html"
    - title: Planificación de la configuración
      url: "/task_planning_your_config.html"
    - title: Busque el ID del sistema
      url: "/task_finding_system_id.html"
    - title: Habilite Flash Cache
      url: "/task_enabling_flash_cache.html"
    - title: Inicie Cloud Volumes ONTAP en AWS
      url: "/task_deploying_otc_aws.html"
    - title: Inicie Cloud Volumes ONTAP en Azure
      url: "/task_deploying_otc_azure.html"
    - title: Inicie Cloud Volumes ONTAP en GCP
      url: "/task_deploying_gcp.html"
    - title: Registre sistemas de pago por uso
      url: "/task_registering.html"
    - title: Configure Cloud Volumes ONTAP
      url: "/task_setting_up_ontap_cloud.html"
  - title: Aprovisionar almacenamiento
    entries:
    - title: Crear volúmenes, agregados y LUN
      url: "/task_provisioning_storage.html"
    - title: Organice en niveles los datos inactivos en el almacenamiento de objetos
      url: "/task_tiering.html"
    - title: Utilice ONTAP como almacenamiento persistente
      url: "/task_connecting_kubernetes.html"
    - title: Cifre los volúmenes con el cifrado de volúmenes de NetApp
      url: "/task_encrypting_volumes.html"
    - title: Gestione el almacenamiento existente
      url: "/task_managing_storage.html"
  - title: Replique y proteja datos
    entries:
    - title: Detectar y gestionar clústeres de ONTAP
      url: "/task_discovering_ontap.html"
    - title: Replicación de datos entre sistemas
      url: "/task_replicating_data.html"
    - title: Realice el backup en Amazon S3
      url: "/task_backup_to_s3.html"
    - title: Sincronice datos con Amazon S3
      url: "/task_syncing_s3.html"
  - title: Obtenga información sobre la privacidad de sus datos
    entries:
    - title: Más información sobre Cloud Compliance
      url: "/concept_cloud_compliance.html"
    - title: Manos a la obra
      url: "/task_getting_started_compliance.html"
    - title: Obtenga visibilidad y control sobre los datos
      url: "/task_controlling_private_data.html"
    - title: Generar informes
      url: "/task_generating_compliance_reports.html"
    - title: Respuesta a un DSAR
      url: "/task_responding_to_dsar.html"
    - title: Deshabilite Cloud Compliance
      url: "/task_managing_compliance.html"
    - title: PREGUNTAS FRECUENTES
      url: "/faq_cloud_compliance.html"
  - title: Administre Cloud Volumes ONTAP
    entries:
    - title: Conéctese a Cloud Volumes ONTAP
      url: "/task_connecting_to_otc.html"
    - title: Actualice el software
      url: "/task_updating_ontap_cloud.html"
    - title: Modificar configuraciones del sistema
      url: "/task_modifying_ontap_cloud.html"
    - title: Pare e inicie los sistemas
      url: "/task_managing_state.html"
    - title: Supervise los costes de AWS
      url: "/task_monitoring_costs.html"
    - title: Mejore la protección contra ransomware
      url: "/task_protecting_ransomware.html"
    - title: Añada los sistemas existentes
      url: "/task_adding_ontap_cloud.html"
    - title: Eliminar sistemas
      url: "/task_deleting_working_env.html"
  - title: Administre Cloud Manager
    entries:
    - title: Actualice Cloud Manager
      url: "/task_updating_cloud_manager.html"
    - title: Gestione la cuenta de Cloud Central
      url: "/task_managing_cloud_central_accounts.html"
    - title: Eliminar entornos de trabajo
      url: "/task_removing.html"
    - title: Configure los ajustes de proxy
      url: "/task_configuring_proxy.html"
    - title: Renueve el certificado HTTPS
      url: "/task_renewing_cert.html"
    - title: Restaure Cloud Manager
      url: "/task_restoring.html"
    - title: Desinstale Cloud Manager
      url: "/task_uninstalling.html"
  - title: Aprovisionamiento de volúmenes para los servicios de archivos
    entries:
    - title: Azure NetApp Files
      url: "/task_manage_anf.html"
    - title: Cloud Volumes Service para AWS
      url: "/task_manage_cvs_aws.html"
  - title: API y automatización
    entries:
    - title: Guía para desarrolladores de API
      url: https://docs.netapp.com/us-en/occm/api.html
    - title: Muestras de automatización
      url: "/reference_infrastructure_as_code.html"
  - title: Referencia
    entries:
    - title: Preguntas más frecuentes sobre la integración de Cloud Central
      url: "/reference_integration_faq.html"
    - title: Configuraciones para Cloud Volumes ONTAP admitidas
      url: https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html
    - title: Regiones admitidas
      url: https://cloud.netapp.com/cloud-volumes-global-regions
    - title: Reglas de grupos de seguridad para AWS
      url: "/reference_security_groups.html"
    - title: Reglas de grupos de seguridad para Azure
      url: "/reference_security_groups_azure.html"
    - title: Reglas de firewall para GCP
      url: "/reference_firewall_rules_gcp.html"
    - title: Páginas de AWS Marketplace
      url: "/reference_aws_marketplace.html"
    - title: Permisos
      url: "/reference_permissions.html"
    - title: Configuraciones predeterminadas
      url: "/reference_default_configs.html"
    - title: Roles de usuario
      url: "/reference_user_roles.html"
    - title: Enlaces relacionados
      url: "/reference_additional_info.html"
  - title: Versiones anteriores
    url: "/reference_earlier_versions.html"
  - title: Avisos legales
    url: "/reference_legal_notices.html"
