---
sidebar: sidebar 
permalink: task_planning_your_config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, byol, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, sc1, premium storage, standard storage, use profile, thin provisioning, deduplication, compression, Cloud Volumes ONTAP explore, Cloud Volumes ONTAP standard, Cloud Volumes ONTAP premium, Cloud Volumes ONTAP byol, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size 
summary: Al poner en marcha Cloud Volumes ONTAP, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o bien puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles. 
---
= Planificación de la configuración de Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Al poner en marcha Cloud Volumes ONTAP, puede elegir un sistema preconfigurado que se ajuste a los requisitos de la carga de trabajo, o bien puede crear su propia configuración. Si elige su propia configuración, debe conocer las opciones disponibles.



== Seleccione un tipo de licencia

Cloud Volumes ONTAP está disponible en dos opciones de precios: De pago por uso y con su propia licencia (BYOL). En el modelo de pago por uso, puede elegir entre tres licencias: Explorar, Standard o Premium. Cada licencia proporciona distintas opciones de computación y capacidad.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_97.html["Configuraciones compatibles para Cloud Volumes ONTAP 9.7 en AWS"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_azure_97.html["Configuraciones compatibles para Cloud Volumes ONTAP 9.7 en Azure"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_97.html["Configuraciones admitidas para Cloud Volumes ONTAP 9.7 en GCP"^]




== Comprender los límites de almacenamiento

El límite de capacidad bruta de un sistema de Cloud Volumes ONTAP está relacionado con la licencia. Los límites adicionales afectan al tamaño de los agregados y los volúmenes. Debe conocer estos límites a medida que planifique la configuración.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_97.html["Límites de almacenamiento para Cloud Volumes ONTAP 9.7 en AWS"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_97.html["Límites de almacenamiento para Cloud Volumes ONTAP 9.7 en Azure"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_97.html["Límites de almacenamiento para Cloud Volumes ONTAP 9.7 en GCP"]




== Elegir una velocidad de escritura

Cloud Manager le permite elegir una configuración de velocidad de escritura para sistemas Cloud Volumes ONTAP de un solo nodo. Antes de elegir una velocidad de escritura, debe comprender las diferencias entre la configuración normal y la alta, así como los riesgos y recomendaciones cuando utilice la alta velocidad de escritura.



==== Diferencia entre la velocidad de escritura normal y la alta velocidad de escritura

Al elegir la velocidad de escritura normal, los datos se escriben directamente en el disco, lo que reduce la probabilidad de que se pierdan los datos en caso de que se produzca una interrupción del servicio no planificada del sistema.

Al elegir una alta velocidad de escritura, los datos se guardan en búfer en la memoria antes de que se escriban en el disco, lo que proporciona un rendimiento de escritura más rápido. Gracias al almacenamiento en caché, existe la posibilidad de perder datos en caso de que se produzca una interrupción no planificada del sistema.

La cantidad de datos que se pueden perder en caso de una interrupción imprevista del sistema es el plazo de dos últimos puntos de coherencia. Un punto de coherencia es el acto de escribir datos en el búfer en el disco. Un punto de coherencia se produce cuando el registro de escritura está completo o después de 10 segundos (lo que ocurra primero). Sin embargo, el rendimiento del volumen de AWS EBS puede afectar el tiempo de procesamiento del punto de consistencia.



==== Cuándo utilizar alta velocidad de escritura

La alta velocidad de escritura es una buena opción si es necesario un rendimiento de escritura rápido para su carga de trabajo, y puede resistir el riesgo de pérdida de datos en caso de una interrupción del servicio del sistema no planificada.



==== Recomendaciones cuando se utiliza una alta velocidad de escritura

Si habilita una alta velocidad de escritura, debe garantizar la protección de escritura en la capa de la aplicación.



== Selección de un perfil de uso de volumen

ONTAP incluye varias funciones de eficiencia del almacenamiento que pueden reducir la cantidad total de almacenamiento que necesita. Al crear un volumen en Cloud Manager, puede seleccionar un perfil que habilite estas funciones o un perfil que las deshabilite. Debe obtener más información sobre estas funciones para ayudarle a decidir qué perfil utilizar.

Las funciones de eficiencia del almacenamiento de NetApp ofrecen las siguientes ventajas:

Aprovisionamiento ligero:: Presenta más almacenamiento lógico a hosts o usuarios del que realmente hay en el pool de almacenamiento físico. En lugar de asignar previamente espacio de almacenamiento, el espacio de almacenamiento se asigna de forma dinámica a cada volumen a medida que se escriben los datos.
Deduplicación:: Mejora la eficiencia al localizar bloques de datos idénticos y sustituirlos con referencias a un único bloque compartido. Esta técnica reduce los requisitos de capacidad de almacenamiento al eliminar los bloques de datos redundantes que se encuentran en un mismo volumen.
Compresión:: Reduce la capacidad física requerida para almacenar datos al comprimir los datos de un volumen en almacenamiento primario, secundario y de archivado.




== Planificación de AWS

Planifique la implementación de Cloud Volumes ONTAP en AWS ajustando el tamaño del sistema y revisando la información de red necesaria para acceder.

* <<Ajuste de tamaño de su sistema en AWS>>
* <<Hoja de trabajo de información de red de AWS>>




=== Ajuste de tamaño de su sistema en AWS

Configurar el tamaño de su sistema Cloud Volumes ONTAP puede ayudarle a cumplir los requisitos de rendimiento y capacidad. Al elegir un tipo de instancia, tipo de disco y tamaño de disco, debe tener en cuenta algunos puntos clave:

Tipo de instancia::
+
--
* Relacione los requisitos de carga de trabajo con el rendimiento máximo y las IOPS para cada tipo de instancia de EC2.
* Si varios usuarios escriben en el sistema al mismo tiempo, elija un tipo de instancia que tenga suficientes CPU para administrar las solicitudes.
* Si tiene una aplicación que está mayormente en lectura, elija un sistema con suficiente RAM.
+
** https://aws.amazon.com/ec2/instance-types/["Documentación de AWS: Tipos de instancias de Amazon EC2"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["Documentación de AWS: Instancias optimizadas para Amazon EBS"^]




--
Tipo de disco de EBS:: Los SSD de uso general son el tipo de disco más común para Cloud Volumes ONTAP. Para ver los casos de uso de discos EBS, consulte http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentación de AWS: Tipos de volúmenes de EBS"^].
Tamaño del disco de EBS:: Es necesario seleccionar un tamaño de disco inicial al iniciar un sistema Cloud Volumes ONTAP. Después de eso, usted puede link:concept_storage_management.html["Permita que Cloud Manager gestione la capacidad de un sistema por usted"], pero si lo desea link:task_provisioning_storage.html#creating-aggregates["cree agregados usted mismo"], tenga en cuenta lo siguiente:
+
--
* Todos los discos de un agregado deben tener el mismo tamaño.
* El rendimiento de los discos EBS está relacionado con el tamaño del disco. El tamaño determina la tasa de IOPS de base y la duración máxima de ráfaga para discos SSD, así como el rendimiento de línea base y de ráfaga para discos HDD.
* En última instancia, debe elegir el tamaño del disco que le proporcione el _rendimiento sostenido_ que necesita.
* Aunque se elijan discos más grandes (por ejemplo, seis discos de 4 TB), es posible que no se obtengan todas las IOPS porque la instancia de EC2 puede alcanzar su límite de ancho de banda.
+
Para obtener más información sobre el rendimiento del disco EBS, consulte http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentación de AWS: Tipos de volúmenes de EBS"^].



--


Consulte el siguiente vídeo para obtener más información acerca de cómo ajustar el tamaño de su sistema Cloud Volumes ONTAP en AWS:

video::GELcXmOuYPw[youtube,width=848,height=480]


=== Hoja de trabajo de información de red de AWS

Al iniciar Cloud Volumes ONTAP en AWS, tiene que especificar detalles acerca de la red VPC. Puede utilizar una hoja de cálculo para recopilar la información del administrador.



==== Información de red para Cloud Volumes ONTAP

[cols="30,70"]
|===
| Información de AWS | Su valor 


| Región |  


| VPC |  


| Subred |  


| Grupo de seguridad (si utiliza el suyo propio) |  
|===


==== Información de red para un par de alta disponibilidad en varios AZs

[cols="30,70"]
|===
| Información de AWS | Su valor 


| Región |  


| VPC |  


| Grupo de seguridad (si utiliza el suyo propio) |  


| Nodo 1 zona de disponibilidad |  


| Subred nodo 1 |  


| Zona de disponibilidad del nodo 2 |  


| Subred nodo 2 |  


| Zona de disponibilidad del mediador |  


| Subred del mediador |  


| Par clave para el mediador |  


| Dirección IP flotante para el puerto de gestión del clúster |  


| Dirección IP flotante para datos en el nodo 1 |  


| Dirección IP flotante para datos en el nodo 2 |  


| Tablas de rutas para direcciones IP flotantes |  
|===


== Planificación de Azure

Planifique la implementación de Cloud Volumes ONTAP en Azure mediante la configuración de su sistema y la revisión de la información de red que debe introducir.

* <<Ajuste de tamaño de su sistema en Azure>>
* <<Hoja de trabajo de información de red de Azure>>




=== Ajuste de tamaño de su sistema en Azure

Configurar el tamaño de su sistema Cloud Volumes ONTAP puede ayudarle a cumplir los requisitos de rendimiento y capacidad. Al elegir un tipo de máquina virtual, un tipo de disco y un tamaño de disco, es necesario tener en cuenta algunos puntos clave:

Tipo de máquina virtual:: Observe los tipos de máquina virtual admitidos en la http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Notas de la versión de Cloud Volumes ONTAP"^] Y, a continuación, revise los detalles sobre cada tipo de máquina virtual admitido. Tenga en cuenta que cada tipo de máquina virtual admite un número específico de discos de datos.
+
--
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv2-series["Documentación de Azure: Tamaños de máquinas virtuales de uso general"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Documentación de Azure: Tamaños de máquinas virtuales optimizadas con memoria"^]


--
Tipo de disco de Azure:: Cuando crea volúmenes para Cloud Volumes ONTAP, debe elegir el almacenamiento en cloud subyacente que Cloud Volumes ONTAP utiliza como disco.
+
--
Los sistemas HA utilizan Blobs de página Premium. Mientras tanto, los sistemas de un solo nodo pueden usar dos tipos de discos gestionados de Azure:

* _Premium SSD Managed Disks_ proporciona un alto rendimiento para cargas de trabajo con un gran volumen de I/o a un coste más elevado.
* _Standard SSD Managed Disks_ proporciona un rendimiento constante para cargas de trabajo que requieren un bajo nivel de IOPS.
* _Standard HDD Managed Disks_ es una buena opción si no necesita un alto nivel de IOPS y desea reducir sus costes.
+
Si quiere más información sobre los casos de uso de estos discos, consulte https://azure.microsoft.com/documentation/articles/storage-introduction/["Documentación de Microsoft Azure: Introducción a Microsoft Azure Storage"^].



--
Tamaño de disco de Azure:: Al iniciar las instancias de Cloud Volumes ONTAP, debe elegir el tamaño de disco predeterminado para los agregados. Cloud Manager utiliza este tamaño de disco para el agregado inicial y para cualquier agregado adicional que cree cuando utilice la opción de aprovisionamiento simple. Puede crear agregados con un tamaño de disco diferente desde el valor predeterminado por link:task_provisioning_storage.html#creating-aggregates["mediante la opción de asignación avanzada"].
+
--

TIP: Todos los discos de un agregado deben tener el mismo tamaño.

Al elegir un tamaño de disco, se deben tener en cuenta varios factores. El tamaño del disco afecta a la cantidad de almacenamiento que se paga, el tamaño de los volúmenes que se pueden crear en un agregado, la capacidad total disponible para Cloud Volumes ONTAP y el rendimiento del almacenamiento.

El rendimiento del almacenamiento Premium de Azure está ligado al tamaño del disco. Los discos más grandes permiten mejorar la tasa de IOPS y el rendimiento. Por ejemplo, elegir discos de 1 TB puede proporcionar un mejor rendimiento que los discos de 500 GB a un coste mayor.

No existen diferencias de rendimiento entre los tamaños de disco para Standard Storage. Debe elegir el tamaño del disco en función de la capacidad que necesite.

Consulte Azure para obtener información sobre IOPS y rendimiento por tamaño de disco:

* https://azure.microsoft.com/en-us/pricing/details/managed-disks/["Microsoft Azure: Precios de discos gestionados"^]
* https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs/["Microsoft Azure: Precios para Blobs de página"^]


--




=== Hoja de trabajo de información de red de Azure

Al implementar Cloud Volumes ONTAP en Azure, tiene que especificar detalles acerca de su red virtual. Puede utilizar una hoja de cálculo para recopilar la información del administrador.

[cols="30,70"]
|===
| Información de Azure | Su valor 


| Región |  


| Red virtual (vnet) |  


| Subred |  


| Grupo de seguridad de red (si utiliza el suyo propio) |  
|===


== Planificación para GCP

Planifique la implementación de Cloud Volumes ONTAP en Google Cloud Platform ajustando el tamaño de su sistema y revisando la información de red a la que debe acceder.

* <<Ajuste de tamaño de su sistema en GCP>>
* <<Hoja de trabajo de información de red para GCP>>




=== Ajuste de tamaño de su sistema en GCP

Configurar el tamaño de su sistema Cloud Volumes ONTAP puede ayudarle a cumplir los requisitos de rendimiento y capacidad. Al elegir un tipo de máquina, un tipo de disco y un tamaño de disco, es necesario tener en cuenta algunos puntos clave:

Tipo de máquina:: Observe los tipos de máquina admitidos en la http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Notas de la versión de Cloud Volumes ONTAP"^] Y luego revise los detalles de Google sobre cada tipo de máquina compatible. Haga coincidir los requisitos de carga de trabajo con el número de vCPU y memoria para el tipo de máquina. Tenga en cuenta que cada núcleo de CPU aumenta el rendimiento de la red.
+
--
Consulte lo siguiente para obtener más información:

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Documentación de Google Cloud: Tipos de máquina estándar N1"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Documentación de Google Cloud: Rendimiento"^]


--
Tipo de disco para GCP:: Cuando crea volúmenes para Cloud Volumes ONTAP, debe elegir el almacenamiento en cloud subyacente que utiliza Cloud Volumes ONTAP para un disco. El tipo de disco puede ser _Zonal SSD persistent disks_ o _Zonal standard persistent disks_.
+
--
Los discos persistentes de SSD son la mejor opción para cargas de trabajo que requieren altas tasas de IOPS aleatorias, mientras que los discos persistentes estándar son económicos y pueden gestionar operaciones de lectura/escritura secuenciales. Para obtener información detallada, consulte https://cloud.google.com/compute/docs/disks/#pdspecs["Documentación de Google Cloud: Discos persistentes zonal (Standard y SSD)"^].

--
Tamaño de discos para GCP:: Debe seleccionar un tamaño de disco inicial al poner en marcha un sistema Cloud Volumes ONTAP. Después puede dejar que Cloud Manager gestione la capacidad de un sistema para usted, pero si desea crear agregados por su cuenta, tenga en cuenta lo siguiente:
+
--
* Todos los discos de un agregado deben tener el mismo tamaño.
* Determine el espacio que necesita, teniendo en cuenta el rendimiento.
* El rendimiento de los discos persistentes se amplía automáticamente con el tamaño del disco y el número de vCPU disponibles para el sistema.
+
Consulte lo siguiente para obtener más información:

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Documentación de Google Cloud: Discos persistentes zonal (Standard y SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Documentación de Google Cloud: Optimización del rendimiento de discos persistentes y SSD locales"^]




--




=== Hoja de trabajo de información de red para GCP

Al implementar Cloud Volumes ONTAP en GCP, debe especificar los detalles de su red virtual. Puede utilizar una hoja de cálculo para recopilar la información del administrador.

[cols="30,70"]
|===
| Información para GCP | Su valor 


| Región |  


| Zona |  


| Red VPC |  


| Subred |  


| Política de firewall (si utiliza la suya propia) |  
|===